### ISSUE TITLE
"walk-speed" flag breaks on server restart

### ISSUE THREAD

**Issue by oskarkk** [aromaa/WorldGuardExtraFlags#168]
1. Create region with `walk-speed` flag set to some speed `x`, other than your normal speed (default: 0.2). You go in, your speed changes to `x` . You go out, your speed goes back to the speed you had before entering the region.
2. Go into the region.
3. Restart the server.
4. Log in, leave the region. Your speed hasn't returned to the previous value, it's still `x`.

Version:
* WorldGuardExtraFlags v4.1.5-SNAPSHOT
* Paper version git-Paper-552 (MC: 1.16.5)
* WorldGuard v7.0.4+f7ff984
* System Info: Java 15 (OpenJDK 64-Bit Server VM 15.0.2+7) Host: Linux 5.10.19-1-MANJARO (amd64)

**Comment by aromaa** [comment]
Was fixed in WorldGuard itself, EngineHub/WorldGuard#1940
