### ISSUE TITLE
kom

### ISSUE THREAD

**Issue by arturek1666** [aromaa/WorldGuardExtraFlags#225]
This function don't work:
console-command-on-entry:
My worldguard file:
`        flags:
            console-command-on-entry: ['/toast %username% -t:goal -icon:spyglass &2you enter vip area']`, the command is not activating when entering an region it broken on the version 4.2.1, works fine on 4.2.0

**Comment by aromaa** [comment]
The bypass wasn't properly checked in 4.2.0 which was fixed in 4.2.1.

**Comment by arturek1666** [comment]
But I am running as console, so it should bypass permissions etc.

**Comment by aromaa** [comment]
You have `/rg bypass` turned on, which means the flags aren't applied to you.

**Comment by arturek1666** [comment]
Ahh I see my bad. Thanks for fast help
