### ISSUE TITLE
command-on-entry doesn't check for y coordinates

### ISSUE THREAD

**Issue by JohnHeikens** [aromaa/WorldGuardExtraFlags#227]
imagine if a region is between y 44 and y 45 but the player goes 'above' the region (x and z are inside but y is above) it will still execute the command.

**Comment by aromaa** [comment]
Not really sure what you mean? If you go though the region while moving it will execute the command. Also the Y position is taken from your feet.

**Comment by JohnHeikens** [comment]
my excuses, it seems to work now.
