### ISSUE TITLE
[Suggestion] New Flag

### ISSUE THREAD

**Issue by DevProdj** [aromaa/WorldGuardExtraFlags#232]
Add a new flag that clears the player's inventory and gives items when the player enters the region and when the player leaves the region revert his inventory back to normal

**Comment by aromaa** [comment]
I intend to keep this plugin pretty simple and this would require at least permanent storage as the player could log out in these regions.

I would suggest finding a plugin which could switch player inventories by using a commands and then take advantage the console-command flags to do it on region switches. Or alternatively move these regions to their own world and use a plugin for per world inventories.
