### ISSUE TITLE
Give-effect prolem...

### ISSUE THREAD

**Issue by Ryguythe2** [aromaa/WorldGuardExtraFlags#233]
For some reason I cant do /region flag (name) give-effects strength 2
It works with every other effect but strength
don't say I typed it wrong I tried 100 different ways and times
is this just not possible or is this a bug. Answer soon 👍 

-sincerely someone

**Comment by rautamiekka** [comment]
Which command does work ?

**Comment by Ryguythe2** [comment]
Speed works

**Comment by Ryguythe2** [comment]
im currently using that

**Comment by aromaa** [comment]
When you enter an invalid type it should link you to [this page](https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/potion/PotionEffectType.html). Unfortunately the type id's use Bukkit names. The one for strength would be `INCREASE_DAMAGE`.

**Comment by rautamiekka** [comment]
> Speed works

I meant the whole command, but glad the dev knew what's wrong.

**Comment by Ryguythe2** [comment]
Thank you so much
