### ISSUE TITLE
Bring back per-flag bypass perms

### ISSUE THREAD

**Issue by JasonHorkles** [aromaa/WorldGuardExtraFlags#234]
I'm not sure if this is still possible with current WorldGuard versions, but having control over the per-flag bypass perms was really useful - would it be possible to bring them back perhaps?

**Comment by aromaa** [comment]
There isn't much need for them anymore. The bypass is easily togglable with the command now days which makes region management easy. And for applying flags to specific group of people can be done with region groups.
