### ISSUE TITLE
[Suggestion] Add a flag to prevent mangrove leaves growing leaves

### ISSUE THREAD

**Issue by HarryOrphic** [aromaa/WorldGuardExtraFlags#237]
Add a flag to prevent mangrove leaves growing leaves

**Comment by aromaa** [comment]
This doesn't belong to here and should be natively implemented in WorldGuard.

**Comment by HarryOrphic** [comment]
i was literally told in the WGEF discord to open an issue suggesting the feature

**Comment by aromaa** [comment]
Maybe there was some confusion but that's not what I meant. I told you to take this up with the EngineHub folks.
