### ISSUE TITLE
Deprecated Behavior

### ISSUE THREAD

**Issue by ItsSynchro** [aromaa/WorldGuardExtraFlags#251]
Hi, I've noticed that using paper 1.19.4 I started getting the following errors. I went ahead and provided the versions I'm using.
https://paste.gg/p/anonymous/e5dfdb9ae4ec4788978f6255a864c9eb

Server Version: Paper 1.19.4
worldguard-bukkit-7.0.8-dist
WorldGuard Extra Flags 4.2.1

**Comment by aromaa** [comment]
Dupe of #236
