### ISSUE TITLE
Regarding "give-effects"

### ISSUE THREAD

**Issue by DreamMiu** [aromaa/WorldGuardExtraFlags#269]
give-effects Specifies whether only one parameter is allowed. Multiple parameters are not allowed

**Comment by aromaa** [comment]
Could you elaborate more what are you trying to ask or which problem are you facing?

**Comment by DreamMiu** [comment]
> 您能否详细说明一下您想问什么或您面临哪些问题？

我需要同时拥有2种药水效果，比如可能存在的命令:"/rg flag -w "world" -h 7 spawn give-effects SPEED:2
JUMP_BOOST:2",事实上他并 不存在

**Comment by DreamMiu** [comment]
> Could you elaborate more what are you trying to ask or which problem are you facing?

I need to have two potion effects at the same time, such as the possible command :"/rg flag -w "world" -h 7 spawn give-effects SPEED:2
JUMP_BOOST:2", in fact he does not exist

**Comment by aromaa** [comment]
Use comma to separate the effects, space for the parameters. `/rg flag -w "world" -h 7 spawn give-effects SPEED 2,
JUMP_BOOST 2`

**Comment by DreamMiu** [comment]
> Use comma to separate the effects, space for the parameters. `/rg flag -w "world" -h 7 spawn give-effects SPEED 2, JUMP_BOOST 2`

It's settled, thank you
